### ISSUE TITLE
php71u-xml missing

### ISSUE THREAD

**Issue by robimac04** [shouptech/ansible-role-nextcloud#1]
For installation of Nextcloud 13.0.2, php71u-xml package is required:

https://github.com/shouptech/ansible-role-nextcloud/blob/81af10becc2f7157ef4ea2d893564d8bdb43aced/tasks/main.yml#L42

**Comment by shouptech** [comment]
Thank you for letting me know! I'm working on updating the role for Nextcloud 13.0.2, and will be fixing this.

**Comment by shouptech** [comment]
Fixed in bbcf20c
